spring:
  webflux:
    base-path: '/spring-security-reactive-rest-api'

feature:
  beta:
    enabled: false

cors:
  origin:
    patterns: "https://example.com,http://example.com,https://*.example.com,http://*.example.com"